//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFFormFiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFFormFiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string btnBrowseInput {
            get {
                return ResourceManager.GetString("btnBrowseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Folder.
        /// </summary>
        public static string btnBrowseOutput {
            get {
                return ResourceManager.GetString("btnBrowseOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Edited PDF.
        /// </summary>
        public static string btnGenerateEditPDF {
            get {
                return ResourceManager.GetString("btnGenerateEditPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Original PDF File and Edited PDF Path are mandatory.
        /// </summary>
        public static string ErrorMessage1 {
            get {
                return ResourceManager.GetString("ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original PDF File.
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited PDF Path.
        /// </summary>
        public static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vanhack {
            get {
                object obj = ResourceManager.GetObject("vanhack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
